version: '{build}'
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - gradlew.bat -v
build_script:
  - gradlew.bat -u -s --no-daemon assemble
test_script:
  - gradlew.bat -u -s --no-daemon check
cache:
  - C:\Users\appveyor\.gradle
